package com.learningJDBC;

import org.springframework.jdbc.core.JdbcOperations;
import org.springframework.stereotype.Repository;

import javax.inject.Inject;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Created by mayz985 on 9/19/17.
 */
@Repository
public class MayRepository {
    private JdbcOperations jdbcOperations;

    @Inject
    public MayRepository(JdbcOperations jdbcOperations) {
        this.jdbcOperations = jdbcOperations;
    }

    public void createTable() {
        String sql = "CREATE TABLE REGISTRATION " +
                "(id INTEGER not NULL GENERATED BY DEFAULT AS IDENTITY(start with 1) , " +
                " first VARCHAR(255), " +
                " last VARCHAR(255), " +
                " age INTEGER, " +
                " PRIMARY KEY ( id ) )";
        jdbcOperations.execute(sql);
        jdbcOperations.execute("select * from REGISTRATION");
    }

    public void insert(MayRegistration registration) {
        String sql = "INSERT INTO Registration(first, last, age) " +
                "VALUES ( ?, ?, ?)";
        jdbcOperations.update(sql,
                registration.first,
                registration.last,
                registration.age);

    }

    public MayRegistration read(int id) {
        String sql = "select first from REGISTRATION where id = ?";

        MayRegistration registrationResult = jdbcOperations.queryForObject(sql, (rs, rowNum) -> {
            MayRegistration registration = new MayRegistration();
            registration.first = rs.getString("first");

            return registration;
        }, id);

        return registrationResult;

    }

    public String readOneColumn(int id) {
        String sql = "select first from REGISTRATION where id = ?";

        String name = (String) jdbcOperations.queryForObject(
                sql, new Object[]{id}, String.class);

        return name;
    }


    public List<MayRegistration> readAll() {
        List<MayRegistration> registrationList = new ArrayList<>();

        String sql = "select * from REGISTRATION";
        List<Map<String, Object>> rows = jdbcOperations.queryForList(sql);
        for (Map row : rows) {
            MayRegistration registration = new MayRegistration();
            registration.first= (String)(row.get("FIRST"));
            registration.last = ((String)row.get("LAST"));
            registration.age = ((Integer)row.get("AGE"));
            registrationList.add(registration);
        }
        return registrationList;
    }

    public void delete(int id) {
        //jdbcOperations.execute();
    }


}
